services:

  mariadb: 
    image: mariadb:1337
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress:1337
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - 9000:9000

  nginx:
    image: nginx:1337
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 443:443
      - 80:80

  

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/youssef/inc/data/mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/youssef/inc/data/wordpress_data
      
networks:
  inception:
    name: inception
    driver: bridge

