services:

  mariadb: 
    image: mariadb:1337
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress:1337
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception

  nginx:
    image: nginx:1337
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 443:443
  
  redis:
    image: redis:1337
    build: ./requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    networks:
      - inception
  
  ftp:
    image: ftp:1337
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/ftp
    ports:
    - 2121:2121
    - 21000-21010:21000-21010

  adminer:
    image: adminer:1337
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    ports:
      - 8080:8080

  game:
    image: game:1337
    build: ./requirements/bonus/jsgame
    container_name: game
    restart: unless-stopped
    networks:
      - inception
    ports:
      - 5000:5000
  
  netdata:
    image: netdata:1337
    build: ./requirements/bonus/netdata
    container_name: netdata
    restart: unless-stopped
    networks:
      - inception
    ports:
      - 19999:19999

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ymahni/data/mariadb_data
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ymahni/data/wordpress_data

networks:
  inception:
    name: inception
    driver: bridge